[[create-job]]
=== create-job

.Purpose

Creates a new Quartz Job class. The general format is:

....
$ grails create-job JOB_CLASS_NAME [--pogo] [--stateful]
....

.Examples

....
$ grails create-job report
....

....
$ grails create-job com.mycompany.foo.priceUpdate --pogo
....

....
$ grails create-job com.mycompany.foo.priceUpdate --stateful
....

....
$ grails create-job com.mycompany.foo.priceUpdate --pogo --stateful
....

.Description

Creates a class with the specified class name and package that implements either `SchwartzJob` or `StatefulSchwartzJob`. By default it will create a stateless class but will make it stateful if you include the `--pogo` flag.

By default the class will be generated as a Grails Service under `grails-app/services`, but if you include the `--pogo` flag the class will be generated under `src/main/groovy`. The plugin doesn't automatically register your job classes as Spring beans, but often job classes need to access the database or call services and other Spring beans. By making your class a Grails Service you get support for dependency injection and can easily make your job class transactional with the `Transactional` annotation. All beans that implement one of the traits will be auto-discovered at startup by `QuartzService` and a `JobDetails` and any configured `Trigger` instances will be registered in the Quartz `Scheduler` if they are not already.
